server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicio_hotel
    ##url: jdbc:postgresql://localhost:3306/microservicio_hotel
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
    # driver: NO USA POSTGRESQL-IMPORTAR DEPENDENCIA postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: API-HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
